### ISSUE TITLE
Java 8

### ISSUE THREAD

**Issue by ricely122** [Marcelektro/MCP-919#1]
Can the java version be switched to Java SE 1.8? I always got 6 rendering errors when changing the version when i was decompiling 1.8.

**Comment by Marcelektro** [comment]
I decompiled and compiled from the source using JDK 8, it worked for me.

**Comment by Marcelektro** [comment]
Can we now close the ticket, or you still have any questions?

**Comment by ricely122** [comment]
yeah we can close it now
