### ISSUE TITLE
Tip

### ISSUE THREAD

**Issue by GlitchedPanda** [Marcelektro/MCP-919#2]
[Deleted]

**Comment by TacoError** [comment]
piss off

**Comment by subodhverma057** [comment]
Yes

**Comment by subodhverma057** [comment]
This is helpful to a lot of people

**Comment by nealol** [comment]
nerd

**Comment by FreeMangoGenerator** [comment]
nerd

**Comment by mhmtnasir** [comment]
> This isnt allowed after the minecraft EULA, you can’t have a decompiled version of minecraft, this is considered pirating. Please remove the pre decompiled files
> 
> Thanks

If this is considered pirating, then Mojang should not have these files open to the web with no auth required.

**Comment by AppleClient** [comment]
i didn't know it was considered pirating

**Comment by Hellscaped** [comment]
> > This isnt allowed after the minecraft EULA, you can’t have a decompiled version of minecraft, this is considered pirating. Please remove the pre decompiled files
> > Thanks
> 
> If this is considered pirating, then Mojang should not have these files open to the web with no auth required.

mojang did not put them to the open web, the client jar is the only one you can access, and it is obfuscated. MCP remaps the obfuscated names to readable ones for devs, and in the MCP TOS it states you cant put it on the internet.

**Comment by mhmtnasir** [comment]
> > > This isnt allowed after the minecraft EULA, you can’t have a decompiled version of minecraft, this is considered pirating. Please remove the pre decompiled files
> > > Thanks
> > 
> > If this is considered pirating, then Mojang should not have these files open to the web with no auth required.
> 
> mojang did not put them to the open web, the client jar is the only one you can access, and it is obfuscated. MCP remaps the obfuscated names to readable ones for devs, and in the MCP TOS it states you cant put it on the internet.

It's simply a ToS violation, not pirating or anything illegal.

**Comment by Hellscaped** [comment]
> > > > This isnt allowed after the minecraft EULA, you can’t have a decompiled version of minecraft, this is considered pirating. Please remove the pre decompiled files
> > > > Thanks
> > > 
> > > 
> > > If this is considered pirating, then Mojang should not have these files open to the web with no auth required.
> > 
> > 
> > mojang did not put them to the open web, the client jar is the only one you can access, and it is obfuscated. MCP remaps the obfuscated names to readable ones for devs, and in the MCP TOS it states you cant put it on the internet.
> 
> It's simply a ToS violation, not pirating or anything illegal.

Could still get the repo DMCA'd by Microsoft.

**Comment by ixnoahlive** [comment]
microsoft owns github smartass

**Comment by Lachrymogenic** [comment]
>uploads decompiled old minecraft version to github
>refuse to elaborate
>minechuds seethe
>repo still not taken down, mojang doesn't care lmfao

hello? based department?
![patrick basedman](https://github.com/Marcelektro/MCP-919/assets/160751404/1a4e43de-28f4-4e05-92d7-3b5dc9ad32bd)

**Comment by Lachrymogenic** [comment]
"atleast include a code of conduct pwease :pleading_face: "

**Comment by GlitchedPanda** [comment]
_
